### ISSUE TITLE
there is some problem in git clone your repository

### ISSUE THREAD

**Issue by xinsir6** [IDEA-Research/HumanArt#4]
![image](https://github.com/IDEA-Research/HumanArt/assets/128811208/9b556f6c-bc06-4094-a2fa-506bfe8f692c)
![image](https://github.com/IDEA-Research/HumanArt/assets/128811208/d4286455-ad63-493b-b3cf-36524a605b54)
I have try many methods to clone your git but failed, includes the method you recommend

**Comment by juxuan27** [comment]
Hi, @xinsir6 ! Thank you for your focus.
I think this may caused by personal environment setting referring [here](https://stackoverflow.com/questions/17683295/git-bash-error-rpc-failed-result-18-htp-code-200b-1kib-s). Moreover, if you want to use the mmpose block in our repo, you can simply go to MMPose repo and we will soon update this repo to the latest version of MMPose. You may see [issue3](https://github.com/IDEA-Research/HumanArt/issues/3) for more detail

**Comment by xinsir6** [comment]
yes，it indeed a personal setting problem, I just upgrade the git version to 2.41 and the bug fix, so the reason may be had to say, it doesn't look like what it report, anyway, you can close the issue

**Comment by xinsir6** [comment]
yes，it indeed a personal setting problem, I just upgrade the git version to 2.41 and the bug fix, so the reason may be had to say, it doesn't look like what it report, anyway, you can close the issue
